//
//  Usermaster.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class Usermaster: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _username: String?
    
    class func dynamoDBTableName() -> String {

        return "ourphotoshare-mobilehub-69061703-usermaster"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_username"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_username" : "username",
        ]
    }
}
