//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_oVfyTfnNe"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "6e5ahf9ulltqkkjmnp3u4qo25e"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = AWSRegionType.USEast1 

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "10tbvaru79gnuj5r0sdm90vkqoqd0tvcvq8p262lpe3h0883apem"
